"""Regenerates schema/ and docs/ from the models. Run after changing world_ir/.

python scripts/build_docs.py
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from pydantic import TypeAdapter  # noqa: E402

from world_ir import Action, World, catalogue  # noqa: E402


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print("wrote", path.relative_to(ROOT))


def model_md(model: dict) -> list[str]:
    title = model["name"]
    if model["tag"]:
        title = f'`{model["tag"]["field"]}: "{model["tag"]["value"]}"` · {model["name"]}'
    lines = [f"#### {title}", "", f'*Tier {model["tier"]}.* {model["summary"]}', ""]
    if not model["fields"]:
        return lines + ["No fields beyond the common ones.", ""]
    lines += ["| Field | Type | Default | Tier | Description |", "|---|---|---|---|---|"]
    for f in model["fields"]:
        notes = f["description"]
        if f["limits"]:
            notes = f"{notes} ({f['limits']})".strip()
        if f["ref"]:
            notes = f"{notes} Refers to: {f['ref']}.".strip()
        if f["repair"]:
            notes = f"{notes} Repair model may edit ({f['repair']}).".strip()
        type_text = f["type"].replace("|", "\\|")
        default = f["default"].replace("|", "\\|")
        lines.append(f"| `{f['name']}` | {type_text} | {default} | {f['tier']} | {notes.replace('|', '/')} |")
    return lines + [""]


def reference_md(cat: dict) -> str:
    out = [
        "# World IR reference",
        "",
        "Generated by `scripts/build_docs.py` from the models in `world_ir/`. Do not edit by hand.",
        "",
        "Tiers: **v1** is needed for the hackathon build, **v2** is stretch, **later** is designed but not planned.",
        "",
        "## Conventions",
        "",
        *[f"- {line}" for line in cat["conventions"]],
        "",
    ]
    for section in cat["sections"]:
        out += [f"## {section['title']}", "", section["intro"], ""]
        for model in section.get("models", []):
            out += model_md(model)
        for group in section.get("groups", []):
            out += [f"### {group['title']}", ""]
            for model in group["models"]:
                out += model_md(model)
        if "presets" in section:
            out += ["### Material presets", "", "| Preset | Values |", "|---|---|"]
            for name, values in section["presets"].items():
                out.append(f"| `{name}` | {', '.join(f'{k}={v}' for k, v in values.items())} |")
            out.append("")
    out += ["## Vocabularies", "", "Suggested values. Fields that use them accept other strings too.", ""]
    for name, values in cat["vocabularies"].items():
        if isinstance(values, dict):
            for sub, items in values.items():
                out.append(f"- **{name} ({sub})**: {', '.join(items)}")
        else:
            out.append(f"- **{name}**: {', '.join(values)}")
    return "\n".join(out) + "\n"


def main() -> None:
    write(ROOT / "schema" / "world.schema.json", json.dumps(World.model_json_schema(by_alias=True), indent=2) + "\n")
    write(
        ROOT / "schema" / "actions.schema.json",
        json.dumps(TypeAdapter(list[Action]).json_schema(by_alias=True), indent=2) + "\n",
    )
    cat = catalogue.build()
    write(ROOT / "docs" / "catalogue.json", json.dumps(cat, indent=2, ensure_ascii=False) + "\n")
    write(ROOT / "docs" / "REFERENCE.md", reference_md(cat))


if __name__ == "__main__":
    main()
