"""Suggested vocabularies. Fields that take these values also accept other strings."""

ROOM_TYPES: list[str] = [
    "bedroom",
    "kids_room",
    "living_room",
    "kitchen",
    "dining_room",
    "bathroom",
    "toilet",
    "office",
    "study",
    "library",
    "hallway",
    "entrance",
    "stairwell",
    "closet",
    "laundry",
    "garage",
    "attic",
    "basement",
    "studio",
    "workshop",
    "classroom",
    "meeting_room",
    "open_office",
    "lobby",
    "shop",
    "cafe",
    "restaurant",
    "bar",
    "gym",
    "clinic",
    "gallery",
    "chapel",
]

ARCHETYPES: dict[str, list[str]] = {
    "interior": ROOM_TYPES,
    "exterior": [
        "forest_clearing",
        "meadow",
        "beach",
        "desert",
        "mountain_pass",
        "lakeside",
        "riverbank",
        "village_square",
        "farmyard",
        "garden",
        "park",
        "city_street",
        "plaza",
        "campsite",
        "ruins",
        "harbour",
        "space_colony",
        "spaceport",
    ],
}

BIOMES: list[str] = [
    "temperate_forest",
    "conifer_forest",
    "grassland",
    "desert",
    "tundra",
    "alpine",
    "tropical",
    "wetland",
    "coastal",
    "urban",
    "lunar",
    "volcanic",
    "alien",
]

STYLE_TAGS: list[str] = [
    "low_poly",
    "stylised",
    "realistic",
    "scandinavian",
    "industrial",
    "mid_century",
    "rustic",
    "japanese",
    "victorian",
    "minimalist",
    "cottage",
    "brutalist",
    "medieval",
    "sci_fi",
    "post_apocalyptic",
]

FUNCTIONS: list[str] = [
    "sleep",
    "sit",
    "work",
    "eat",
    "cook",
    "store",
    "display",
    "wash",
    "light",
    "decorate",
    "play",
    "exercise",
]
